modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "Insert License Here"


[[mods]]
modId = "immersive_weathering"
version = "${version}"
displayName = "Immersive Weathering"
authors = "Me!"

logoFile="assets/immersive_weathering/icon.png" #optional
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.immersive_weathering]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.immersive_weathering]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,)"
ordering = "NONE"
side = "BOTH"
